jobs:
  include:
    - language: java
    java:
      - os: linux
      - dist: trusty
      - jdk: oraclejdk11

    before_install:
      - chmod +x gradle

    script:
      - ./gradlew stage

    - language: node_js
      node_js:
        - 15

    before_script:
      - cd melody-website

    script:
      - yarn build