site:
  about:
    siteName: 'Melody'
    subtitle: 'All your melody bot needs in one website!'
    siteDescription: 'Here you can access the documentation and posts about the melody discord bot!'
    avatar: '/assets/media/logo.jpg'
  theme: 'Editorial'
  baseUrl: '/home'

theme:
  social:
    facebook: 'facebookUsername'
    twitter: 'twitterHandle'
    instagram: 'instagramHandle'
    github: 'DisBots-Studios-Inc/Melody-Bot'
    other:
      - label: 'linkedin'
        link: 'https://www.example.com'
        icon: 'fa-tag'
  menu:
    - type: 'page'
      title: 'Home'
      url: '/home'
    - type: "wikiSections"
    - type: 'taxonomy'
      taxonomyType: 'categories'
      includeTerms: true
      termsAtRoot: true
    - type: 'page'
      title: 'About'
      itemId: 'Game-Glide'
    - type: "pages"
      atRoot: true
    - type: groupPages
      collectionType: pages
      collectionId: allPages
  sidebar:
    - type: recentPosts
      limit: 3
      category: gallery
      noWrapper: true
      template:
        - 'includes/postPreview_mini'
    - type: recentPosts
      limit: 5
      category: personal
      noWrapper: true
      template:
        - 'includes/postPreview_list'
  extraCss:
    - 'assets/css/extraCss.scss'
    - 'assets/css/pygments.scss'
  extraJs:
    - 'assets/js/extraJs.js'
  legacySearch: false
  metaComponents:
    - type: orchidSearch

services:
  generators:
    externalIndices:
      - 'https://orchid.run/meta/all.index.json'
